### ISSUE TITLE
a11y: Speak region causes page overflow

### ISSUE THREAD

**Issue by aduth** [WordPress/packages#38]
The `@wordpress/a11y` module adds an element container to the page which acts as a target for `speak` text. However, its current styling will cause overflow (scroll) on the page when inserted as a sibling of `#wpwrap`.

https://github.com/WordPress/packages/blob/fd7fff1458f740204cc4e4ee2dfdb804a1c8c38b/packages/a11y/src/addContainer.js

__Steps to reproduce:__

1. With the [Gutenberg](https://wordpress.org/plugins/gutenberg/) plugin installed, navigate to Gutenberg > New Post in the admin dashboard
2. Open your developer tools console
3. Remove all nodes except `#wpwrap` and `.a11y-speak-region`
   - `[ ...document.body.querySelectorAll( ':not( #wpwrap ):not( .a11y-speak-region )' ) ].forEach( ( node ) => node.parentNode.removeChild( node ) );`

__Expected:__ No scroll on page
__Actual:__ Scroll on page

We should seek to either:

- Append `.a11y-speak-region` within `#wpwrap`
- Style `.a11y-speak-region` in such a way to not occupy any space

cc @omarreiss

**Comment by afercia** [comment]
The screen-reader-text used by this module is slightly different from the one used by core. It needs also `margin-top: -1px;`.

**Comment by aduth** [comment]
I worked around this in https://github.com/WordPress/gutenberg/pull/2800 by positioning the element at `top: -1px; left: -1px;` (off screen in this direction causes no overflow).

**Comment by afercia** [comment]
I wouldn't position it, since this may have an impact on some screen readers. Sounds weird, but especially VoiceOver under some conditions takes into account the elements position (noticed a few times with other usages of screen-reader-text).

**Comment by aduth** [comment]
@afercia Is this visual positioning (like x, y offset) or position relative other elements in the DOM? Do you have any resources which I can reference?

**Comment by afercia** [comment]
@aduth the Speak thing using aria live regions is pretty "experimental", I don't think there are great resources around other than general ones explaining how to use live regions. Re: the position issue, what I've noticed a few times in other projects is VoiceOver taking into account the position of visually hidden elements, for example in this case, the visually hidden text is after the visible text but positioned "on top":

<img width="1376" alt="6b619f2e-31d2-11e7-9d7a-b2e8040c5d59" src="https://user-images.githubusercontent.com/1682452/30899709-555d8ef8-a361-11e7-940c-84968fa1d5da.png">

and VoiceOver reads out the visually hidden text before... ignoring the source order:

<img width="785" alt="563f3156-31d2-11e7-9b68-cf881427abd0" src="https://user-images.githubusercontent.com/1682452/30899610-dc394152-a360-11e7-908d-4ad8959c68df.png">

So my recommendation is to keep the hidden aria live regions positioned at the bottom of the page. Regardless, `@wordpress/a11y` is a module and should work out of the box without requiring fixes during implementation. Other people using the module could face the same bug, so I'd say it should be fixed in the module.

**Comment by aduth** [comment]
>Regardless,` @wordpress/a11y` is a module and should work out of the box without requiring fixes during implementation. Other people using the module could face the same bug, so I'd say it should be fixed in the module.

Oh, certainly, the fix I included in Gutenberg was only meant as a temporary workaround. And since I'd merged it already before knowing the positioning issue, I think I'll go ahead and introduce the fix here and update Gutenberg accordingly.

**Comment by afercia** [comment]
Sure. Inspired by this, I've quickly checked a few places in the WP admin and the absolute positioning is actually triggering the Safari 10/11 + VoiceOver bug on some elements:

![screen shot 2017-09-27 at 11 36 10](https://user-images.githubusercontent.com/1682452/30913731-7b5fba7e-a391-11e7-98ec-588d9ee83c1e.png)

notice the text `(opens in a new window)` comes after the visible text in the source but VoiceOver reads out it before...
Will open a Trac ticket.
